changelog:
  exclude:
    labels:
      - Main
    authors:
      - octocat
  categories:
    - title: 🆕 새로운 기능이 추가되었어요!
      labels:
        - ✨ Feature
    - title: 🐞 자잘한 버그를 수정했습니다.
      labels:
        - 🐞 Bugfix
    - title: 🫶🏻 앱 사용성 개선에 힘썼습니다.
      labels:
        - 🫶🏻 Improvement
    - title: 🛠️ 더 나은 코드를 위해 노력하고 있습니다.
      labels:
        - 🔨 Refactor
        - ⚙️ Setting
    - title: Others
      labels:
        - "*"
