version: '3'
services:
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444"
  app:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - ONEUL_URL=https://www.instagram.com/oneul_sikdang/
      - JUNGBAN_URL=https://pcmap.place.naver.com/restaurant/1671594903/feed
    ports:
      - "3000:3000"